[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Arbitrum Sepolia configuration
[rpc_endpoints]
arbitrum_sepolia = "${RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
