[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
nika_treasury = "EkEP6vRisXSE4TSBDvr8FcpzZgSaYeVKc9uRdFpnXQVB"

[programs.devnet]
nika_treasury = "EkEP6vRisXSE4TSBDvr8FcpzZgSaYeVKc9uRdFpnXQVB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./devnet-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
